apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCB+S2dSMK9n0XPL68S7VjFqk6NVz30mF0syxpK5ztmOfDtAp1pY/dFVZiRBUGG86o0aYZfiK3ZuwfFZ81/AAm4RTlrEJ7lNNhlnaA0cfoepgdZGx4mqIUDmpdKxI4THIqLuciP7mx+4J0qgYIGaJzpjsRj72+8fhPXGuXXGWNif2CEO1jEBLznr/gQWzE71qs3MvXaYJL2bRO+tkr+9To4Ekb8pwqJnJjZLufYtSvRaGbilnyZUzAQ+pNC6cREXrVQNvaxUmVE3eNHli/0QeCSyN96adugJgyM31h9LJnP2leSjJIVEae5mX0A1oQsbXXgr0n74yOXZCuI3HcLYQSa+bp8ycGtupsRJoAnQZF5s9rA76jH0SVHK2/sO42QMNymfayCS2GMSooVYbKZZSf4P0xuoq7opltcYsz7lPilVo0OiH3zIc4aKIAgZlPbOxhTJu/jsQBbQ98GNqvnWjaMTai080H/AWv+jVc2IiUuEYYOBmPi1TL9ekTksASsCC+hYr3EHpNcTujMY1gEAtwf3i+vjY5qBGo7O/NijNgGru8eM0Pc1UIoF/wlkH2IjZm1FFTisZwJ24+yaA9ZCtFhFNH8v44+CXta1NMzt/nlnn/TfbG/DK7U3y3kETOPbH8Bp35k3N7RizZidGG20+AH/NiUVZpS1703sVp0HzyyYDcXDI/s7Afl/ouQtpX5Z3lb/4RSIEhpf9pKdg==
  template:
    metadata:
      creationTimestamp: null
      name: database
      namespace: default

